### ISSUE TITLE
Add clearing options

### ISSUE THREAD

**Issue by immanuelqrw** [immanuelqrw/GitBase#19]
### Description
Add option to remove all of a category (label, issue, milestone, etc.)

### Details
Resetting a repositories issues and labels is common when returning to an untouched repository after a long time. Being able to reset project information without deleting the project would save time.

### Acceptance Criteria
- Removable labels
- Removable milestones
- Removable issues

### Tasks

- [ ] Add removeLabels method
- [ ] Add removeMilestones method
- [ ] Add removeIssues Method
- [ ] Add configuration options
