### ISSUE TITLE
Add option to create Organization Repository

### ISSUE THREAD

**Issue by immanuelqrw** [immanuelqrw/GitBase#20]
### Description
Add an option to allow creation of owned Organization repositories

### Details
Creating an Organization repository is possible through `github-api` but is a separate method. So currently requires transferring ownership of each repository after creation. It would be simpler to include a method to create directly.

### Acceptance Criteria
- Can create repository for Organization directly without requiring transfer of ownership
- Will only require a boolean toggle and possibly an organization name

### Tasks

- [ ] Add option to repository-init.yaml
- [ ] Add method to create organization repository
- [ ] Include method in main
